version: '3'
services:
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
volumes:
  node_modules:

