name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWD }}
        
    - name: build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: Dockerfile
        tags: main
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=registry.nanamiiiii.dev/nanamiiiii-dev:cache
        cache-to: type=registry,ref=registry.nanamiiiii.dev/nanamiiiii-dev:cache,mode=max
